SELECT *
FROM (
    SELECT  ROW_NUMBER() OVER (PARTITION BY PAF.PERSON_NUMBER 
                               ORDER BY AS2.EFFECTIVE_START_DATE DESC) AS RN,
            PAF.PERSON_NUMBER,
            PAF.PERSON_ID,
            AS2.ASSIGNMENT_NUMBER,
            AS2.EFFECTIVE_START_DATE,
            AS2.EFFECTIVE_END_DATE,
            AS2.GRADE_ID,
            AS2.ASSIGNMENT_NAME,
            AS2.ASSIGNMENT_STATUS_TYPE,
            MAX(AS2.EFFECTIVE_END_DATE) OVER (PARTITION BY PAF.PERSON_NUMBER) AS MAX_END_DATE
    FROM    PER_ALL_PEOPLE_F PAF
    JOIN    PER_ALL_ASSIGNMENTS_M AS2
           ON AS2.PERSON_ID = PAF.PERSON_ID
          AND (AS2.ASSIGNMENT_TYPE LIKE 'E%' OR AS2.ASSIGNMENT_TYPE LIKE 'C%')
          AND (AS2.ASSIGNMENT_TYPE NOT LIKE 'ET%' AND AS2.ASSIGNMENT_TYPE NOT LIKE 'CT%')
    WHERE   SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
      AND   (PAF.PERSON_NUMBER LIKE :PERSON_NUMBER OR :PERSON_NUMBER IS NULL)
)
-- WHERE (
--         -- Case 1: end_date is null → use sysdate
--         (:END_DATE IS NULL AND SYSDATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE)

--         -- Case 2: end_date within some assignment
--      OR (:END_DATE IS NOT NULL AND :END_DATE BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE)

--         -- Case 3: end_date beyond everything → take open-ended row (4712)
--      OR (:END_DATE IS NOT NULL AND :END_DATE > MAX_END_DATE AND EFFECTIVE_END_DATE = DATE '4712-12-31')
-- )
-- AND RN = 1;